language: node_js
services:
  - redis-server
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - redis-cli set tb_api_secret 123
  - redis-cli set tb_api_key 123
addons:
  firefox: "latest"
