language: node_js
services:
  - redis-server
install:
  - npm install;
    npm install travis-github-lint-status;
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - eval $CMD
env:
  - CMD="./node_modules/travis-github-lint-status/index.js"
  - CMD="npm run test" TB_API_SECRET=123 TB_API_KEY=123
addons:
  firefox: "latest"
